  
env:
  node: true
  commonjs: true
  mocha: true
  es6: true
extends:
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  array-bracket-newline: ["warn", {"multiline": true, "minItems": 2}],
  block-spacing: ["warn", "always"],
  brace-style: ["warn", "stroustrup", {"allowSingleLine": true}],
  arrow-spacing: ["warn", {"before": true, "after": true}],
  no-process-env: "off",
  no-duplicate-imports: "error",
  semi: ["warn", "always"],
  func-call-spacing: ["warn", "never"],
  keyword-spacing: ["warn", { "before": true }],
  key-spacing: ["warn", { "beforeColon": false }]
}